---
title: "Bootstrappign"
author: "Abigail Bar"
date: "4/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
### Create figs + bootstrap for CI's

### Initialize Workspace -------------------------------------------------------
rm(list = ls()) #clear workspace

 
library(ggplot2) #for plotting
library(patchwork) #joins plots nicely
library(tidyverse) #you'll prob. need this
library(parallel) #allows bootstrapping in parallel
library(stats) #for quantile extraction



#load models

meanMAP <- readRDS("modeloutput/avgplant.RDS") #insert the path to each RDS object into the parenthesis
minMAP <- readRDS("modeloutput/minplant.RDS")
rangeMAP1 <- readRDS("modeloutput/rangeplant.RDS")

#load data
dat <- read.csv("data/livedifference.csv")

### Create Predictions for plotting --------------------------------------------

## I'm going to do a tutorial for "meanMAP" and then you'll want to copy/paste
## and customize the code for minMAP and rangeMAP

#Make predictions --------------------------------------------------------------

# first, you make a dataframe to keep your model predictions (the mean estimates)
# expand.grid will take each component you give it, and create a dataframe
# where each value of hostorigin is associated with each value of pathogenorigin.
# "preddat" must contain every fixed effect that is in your model. I am giving it
# a range of values for host origin because that will be our x-axis and the line
# we plot, and I'm giving it a single value for pathogenorigin (I choose the mean)
# because we no there is no effect and we don't need to bootstrap on multiple
# values of pathogen origin for this model. In later models you will want 2-3 
# values of pathogen origin. I usually pick the 10th, 50th, and 90th quantiles. 

preddat <- expand.grid((hostorigin = seq(1800,3000, 200)), pathogenorigin = quantile(dat$pathogenorigin, probs = 0.5))
#quantile(dat$pathogenorigin, probs = c(0.1,0.5,0.9))
#check your data on host origin. Does a ~min of 1800mm/yr + ~max of 3000mm/yr make sense?
# next, make predictions from the mean estimates of the model using preddat values.
# re.form = ~0 tells predict to ignore your random effects. Keep this.

preddat$preds <- predict(meanMAP, newdata = preddat, re.form = ~0) 


### Bootstrapping --------------------------------------------------------------
# now it's time to bootstrap to get the CI's around the estimate. Because you've
# used a linear model this will be pretty quick (maybe 30 seconds) a glmm would take
# a few hours to run. 

## Bootstrapping Code
#Create cluster within computer to bootstrap in parallel
cl <- makeCluster(detectCores()) 
clusterEvalQ(cl, library(lme4))

# this first step contains some stuff that should look familiar. Preddat should 
# be identical here to the one above. However, "quantile" won't work within a function.
# run quantile(dat$pathogenorigin,probs = 0.5) alone to get the absolute value
# and plug it into the preddat below. It'll be something like 2311 or 2595.
quantile(dat$pathogenorigin,probs = 0.5)
pred.fun <- function(.) {
 preddat <- expand.grid(hostorigin = seq(1800,3000, 200), 
  pathogenorigin = 2595)
  predict(., newdata = preddat, re.form = ~0)
}

#make sure the names are correct here, but you should be able to just run this now.
meanMAP.boot <- bootMer(meanMAP, nsim = 1000, FUN = pred.fun,
                     parallel="snow", ncpus = detectCores(), 
                     cl=cl)

#create a folder called "bootoutput" or something to save the files...

#save the output!
save(meanMAP.boot, file = "bootoutput/meanMAP.boot")

#stop the clusters when you finish,
#or else your computer will have permanently wonky memory allocation
stopCluster(cl = cl) 

### Combine predictions and CIs ------------------------------------------------

#merging bootstrapped confidence intervals

#I usually have separate scripts for bootstrapping and making figs, so it makes
#sense for me to save and load. My boots are also on glmm so saving the output saves me hours.
#this is still useful to you, but with this bit you wouldn't need to run the boostrapping
#every time. It's up to you if you ultimately prefer to have all the boostrapping
#in a separate doc or combined. 
load("bootoutput/meanMAP.boot") 

preddat<- data.frame(preddat, confint(meanMAP.boot))

#just guessing here on the numbers. The final 2 columns of preddat will be lwr and upr.
#Make sure the numbers reflect the final 2 columns that you need to rename.

names(preddat)[4:5] <- c("lwr", "upr")  

### Plot it --------------------------------------------------------------------

# below is the basic structure that I'd use for plotting. geom_ribbon (for the CI's)
# must come before geom_line. I've left this intentionally sparse so that you can
# make your own aesthetic decisions, and if you google for how to set each up you
# should be able to make a plot pretty quickly. Nothing needs to go in the () of
# theme_classic, and it should always be at the end. (you can pick another theme,
# but I like this one for its simplicity).


meanplot <- preddat %>% ggplot(aes(x=Var1, y=preds)) +
  geom_ribbon(aes(min=lwr, max = upr), alpha = 0.3, fill = 'blue') + 
  geom_line(color='blue', size = 1.2) + 
  xlab("Avg Plant Species Location \n by Preciptation (mm)") +
  ylab("Percent Leaf Infection") +
  theme(axis.title = element_text(size = 16),
        axis.text = element_text(size=12)) +
  theme_classic()
#increase size for presentation

meanplot #how does it look?

#save it when you like it!

#make a figures folder.

ggsave("figures/meanMAP.jpeg", plot = meanplot,
       height = 8, width = 12, units = "in") 




```

```{r range}
preddat1 <- expand.grid((rangeMAP = seq(200,1600, 200)), pathogenorigin = scale(quantile(dat$pathogenorigin, probs = c(0.1,0.9))))
preddat2 <- expand.grid((rangeMAP = seq(200,1600, 200)), pathogenorigin = quantile(dat$pathogenorigin, probs = 0.9))

#check your data on host origin. Does a ~min of 1800mm/yr + ~max of 3000mm/yr make sense?
# next, make predictions from the mean estimates of the model using preddat values.
# re.form = ~0 tells predict to ignore your random effects. Keep this.

preddat1$preds <- predict(rangeMAP1, newdata = preddat1, re.form = ~0)
preddat2$preds <- predict(rangeMAP1, newdata = preddat1, re.form = ~0)

preddat3 <- rbind(preddat1,preddat2)
### Bootstrapping --------------------------------------------------------------
# now it's time to bootstrap to get the CI's around the estimate. Because you've
# used a linear model this will be pretty quick (maybe 30 seconds) a glmm would take
# a few hours to run. 

## Bootstrapping Code
#Create cluster within computer to bootstrap in parallel
cl <- makeCluster(detectCores()) 
clusterEvalQ(cl, library(lme4))

# this first step contains some stuff that should look familiar. Preddat should 
# be identical here to the one above. However, "quantile" won't work within a function.
# run quantile(dat$pathogenorigin,probs = 0.5) alone to get the absolute value
# and plug it into the preddat below. It'll be something like 2311 or 2595.
quantile(dat$pathogenorigin,probs = c(0.1,0.9))
pred.fun1 <- function(.) {
 preddat1 <- expand.grid(hostorigin = seq(1800,3000, 200), 
  pathogenorigin = c(1874,3203))
  predict(., newdata = preddat3, re.form = ~0)
}

#make sure the names are correct here, but you should be able to just run this now.
rangeMAP.boot <- bootMer(rangeMAP1, nsim = 1000, FUN = pred.fun1,
                     parallel="snow", ncpus = detectCores(), 
                     cl=cl)

#create a folder called "bootoutput" or something to save the files...

#save the output!
save(meanMAP.boot, file = "bootoutput/meanMAP.boot")

#stop the clusters when you finish,
#or else your computer will have permanently wonky memory allocation
stopCluster(cl = cl) 

### Combine predictions and CIs ------------------------------------------------

#merging bootstrapped confidence intervals

#I usually have separate scripts for bootstrapping and making figs, so it makes
#sense for me to save and load. My boots are also on glmm so saving the output saves me hours.
#this is still useful to you, but with this bit you wouldn't need to run the boostrapping
#every time. It's up to you if you ultimately prefer to have all the boostrapping
#in a separate doc or combined. 
load("bootoutput/meanMAP.boot") 

preddat<- data.frame(preddat, confint(meanMAP.boot))

#just guessing here on the numbers. The final 2 columns of preddat will be lwr and upr.
#Make sure the numbers reflect the final 2 columns that you need to rename.

names(preddat)[4:5] <- c("lwr", "upr")  

### Plot it --------------------------------------------------------------------

# below is the basic structure that I'd use for plotting. geom_ribbon (for the CI's)
# must come before geom_line. I've left this intentionally sparse so that you can
# make your own aesthetic decisions, and if you google for how to set each up you
# should be able to make a plot pretty quickly. Nothing needs to go in the () of
# theme_classic, and it should always be at the end. (you can pick another theme,
# but I like this one for its simplicity).




ggsave("figures/meanMAP.jpeg", plot = meanplot,
       height = 8, width = 12, units = "in") 


rangeplot <- preddat %>% ggplot(aes(x=Var1, y=preds)) +
  geom_ribbon(aes(min=lwr, max = upr), alpha = 0.3, line = pathogenorigin, color = pathogenorigin, fill = pathogenorigin) + 
  geom_line(color= pathogenorigin, size = 1.2) + 
  xlab("Avg Plant Species Location \n by Preciptation (mm)") +
  ylab("Percent Leaf Infection") +
  theme(axis.title = element_text(size = 16),
        axis.text = element_text(size=12)) +
  theme_classic()

```
